FROM ubuntu:22.04

LABEL dock.schema-version="0.1"
LABEL dock.img.name="annobrainer-docker-image"
LABEL dock.img.description="Docker image for annoBrainer opensource"
LABEL dock.maintainer.name="dped-imaging"
LABEL dock.maintainer.isid="navratjo"
LABEL dock.maintainer.email="josef.navratil@msd.com"
LABEL dock.maintainer.team="Central Software Engineering"
LABEL dock.maintainer.division="Prague IT"
LABEL dock.docker.run='docker run -it -v "${STATIC_DIR_PATH}/static_data:/static_data" -v "${DATA_DIR_PATH}/Example:/input" --gpus all annobrainer:0.1 /annoBrainer/run_annobrainer.sh'

RUN apt-get update && apt-get install -yq --no-install-recommends
RUN apt install python3 python3-pip libpangocairo-1.0-0 ffmpeg libsm6 libxext6  -y
RUN mkdir allen_downloader
ADD download_allen_atlas_data.py /allen_downloader
ADD requirements-atlas.txt /allen_downloader
RUN cd /allen_downloader && python3 -m pip install -r requirements-atlas.txt
CMD ["/allen_downloader/download_allen_atlas_data.py"]
ENTRYPOINT ["python3"]